<?php


$CART_postage="CREATE TABLE IF NOT EXISTS CART_postage
(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
postage01 mediumtext NOT NULL,
postage02 VARCHAR(100) NOT NULL,
postage03 VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8";

$CART_orderlist="CREATE TABLE IF NOT EXISTS CART_orderlist
(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,

date VARCHAR(100) NOT NULL,
customer_id VARCHAR(100) NOT NULL,
ordernumber VARCHAR(100) NOT NULL,
name VARCHAR(100) NOT NULL,
kana VARCHAR(100) NOT NULL,
zip VARCHAR(100) NOT NULL,
addr VARCHAR(100) NOT NULL,
tel VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,

name2 VARCHAR(100) NOT NULL,
zip2 VARCHAR(100) NOT NULL,
addr2 VARCHAR(100) NOT NULL,
tel2 VARCHAR(100) NOT NULL,

payment VARCHAR(100) NOT NULL,
comment VARCHAR(100) NOT NULL,

orderdata LONGTEXT NOT NULL,
charge VARCHAR(100) NOT NULL,
postage VARCHAR(100) NOT NULL,
commission mediumtext NOT NULL,
total VARCHAR(100) NOT NULL,
consumption_tax VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
)  DEFAULT CHARACTER SET utf8";

$CART_customerlist="CREATE TABLE IF NOT EXISTS CART_customerlist
(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
name VARCHAR(100) NOT NULL,
kana VARCHAR(100) NOT NULL,
zip VARCHAR(100) NOT NULL,
pref VARCHAR(100) NOT NULL,
address VARCHAR(100) NOT NULL,
tel VARCHAR(100) NOT NULL,
fax VARCHAR(100) NOT NULL,
mailaddress1 VARCHAR(100) NOT NULL,
password1 VARCHAR(100) NOT NULL,
name2 VARCHAR(100) NOT NULL,
zip2 VARCHAR(100) NOT NULL,
pref2 VARCHAR(100) NOT NULL,
address2 VARCHAR(100) NOT NULL,
tel2 VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
)  DEFAULT CHARACTER SET utf8";

$CART_commission="CREATE TABLE IF NOT EXISTS CART_commission
(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
name mediumtext NOT NULL,
form mediumtext NOT NULL,
charge VARCHAR(100) NOT NULL,
comment mediumtext NOT NULL,
PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8";

$CART_cartedit="CREATE TABLE IF NOT EXISTS CART_cartedit
(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
set01 VARCHAR(100) NOT NULL,
set02 VARCHAR(100) NOT NULL,
set03 VARCHAR(100) NOT NULL,
set04 mediumtext NOT NULL,
set05 VARCHAR(100) NOT NULL,
set06 mediumtext NOT NULL,
PRIMARY KEY (id)
)  DEFAULT CHARACTER SET utf8";
?>